### ISSUE TITLE
Stop training the context during train_G/train_D?

### ISSUE THREAD

**Issue by ntubertchen** [guxd/DialogWAE#1]
I find it reasonable to stop training utterance encoder when training generator and discriminator.

However, why don't you shut down context encoder as well?

Is there any specific consideration?

Thanks.

**Comment by guxd** [comment]
We considered this issue and tried such training strategy. However, the performance looks worse. 
I think if we shut down context encoder, the auto-encoder is just independent to the GAN module thus cannot be regularized by the WAE.
You can still try it and let us know any better strategies.

**Comment by ntubertchen** [comment]
Thanks for the quick reply.

So how about turning both utterance encoder and context encoder on during training generator and discriminator.

I assume you had tried such strategy and got worse performance. I would like to ask how bad it became when utterance encoder was turned on.  Was the drop significant?

This paper proposed an interesting thought, nice work.

**Comment by guxd** [comment]
I did that! Please be noted that the context encoder contains the utterance encoder, 
```
self.context_encoder = ContextEncoder(self.utt_encoder, config['n_hidden']*2+2, config['n_hidden'], 1, config['noise_radius'])
```
so whenever we update the context encoder, the utterance encoder will be updated as well.
