### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by ntubertchen** [guxd/DialogWAE#2]
![image](https://user-images.githubusercontent.com/7036778/44947317-07640180-ae3e-11e8-9675-86f29b17b1dc.png)

Hi, I want to ask about your code.
What does backward(one) or backward(minus_one) do here.

**Comment by guxd** [comment]
one means gradient descending, which finds the minimum function value, while minus one means gradient ascending, which aims to find the maximum function value.

**Comment by ntubertchen** [comment]
Then why is that the generator of VAE and the generator of GAN have exactly the opposite objective function.
Shouldn't both generator try to trick discriminator? So the update direction of both model were supposed to be the same.

**Comment by guxd** [comment]
They are just made opposite to minimize D(G(z_prior,c),c) - D(Q(z_post, c), c)
