### ISSUE TITLE
Confused about the evaluation of inter-dist metrics.

### ISSUE THREAD

**Issue by hengyicai** [guxd/DialogWAE#6]
Hi, thanks for your insightful work! 
I'm confused about the evaluation of inter-dist metrics in the ``sample.py'', as follows (simplified):

```
while True:
    batch = test_loader.next_batch()  # batch_size is 1 here
    ...
    intra_dist1, intra_dist2, inter_dist1, inter_dist2 = metrics.div_distinct(sample_words, sample_lens)
    inter_dist1s.append(inter_dist1)
    inter_dist2s.append(inter_dist2)
    ...
inter_dist1 = float(np.mean(inter_dist1s))
inter_dist2 = float(np.mean(inter_dist2s))
print("inter_dist1 %f, inter_dist2 %f" % (inter_dist1, inter_dist2))
print("Done testing")
```

I understand that that inter_dist is computed regarding #n_samples predictions in the `metrics.div_distinct()`. However, shouldn't this inter_dist be calculated on the entire test set?
That is, **inter_dist1 = #distinct_unigram/#total_unigram**.  From the code, it seems that the inter_dist just measures the single batch, and averages the results. Besides, the batch_size is 1 here, so the inter_dist only measures #n_samples predictions (#n_samples=5 in the code). If #n_samples == 1, then the inter_dist is equivalent to the intra_dist?

Hoping for your replies! Thanks ahead!

**Comment by guxd** [comment]
Thanks for your interest! 
inter_dist is computed regarding each batch (batch size=1). We want to evaluate how many distinct n-grams the model generates for each context rather than all contexts. #n_samples is always greater than 1 in our evaluation. 

We averaged the results for all batches in the test set.

**Comment by hengyicai** [comment]
Thanks for your reply!
Since DialogWAE samples multiple responses for each context, the inter_dist makes its sense.
However, for other deterministic models, i.e., HRED, only one response is generated for the given context.
Thus, does the inter_dist metric for those models computed regarding all contexts?

**Comment by guxd** [comment]
For deterministic models, we repeated each generated response for n_samples times.
I think it is equivalent to compute regarding all contexts.

**Comment by hengyicai** [comment]
Thanks for your patient explanations!
