### ISSUE TITLE
Warning when run sample.py：RNN module weights are not part of single contiguous chunk of memory. 

### ISSUE THREAD

**Issue by hejunqing** [guxd/DialogWAE#7]
After training for 100 epoch，I try to test the performance of models using the sample.py. 
The first question is: which metric should I use to select the best model? The BLEU precision keeps decreasing while the recall reach the highest point at 88th epoch. I am a freshman in GAN. 

Then I decided to find the best performer by testing the models. Here comes the problem: 

/search/odin/hejunqing/DialogWAE/modules.py:86: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  hids, h_n = self.rnn(inputs, init_hidden)
/search/odin/hejunqing/DialogWAE/modules.py:141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  hids, h_n = self.rnn(utt_floor_encs, init_hidden)
/search/odin/hejunqing/DialogWAE/modules.py:289: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  decoder_output, decoder_hidden = self.rnn(decoder_input, decoder_hidden)

These warnings appear when I run sample.py. with pytorch 0.4.0.

**Comment by guxd** [comment]
you can use f1-bleu to select the best model.
You can try calling flatten_parameters() before calling self.rnn().

**Comment by hejunqing** [comment]
Thanks! I add .cuda() after load model then the warning disappear. The valid AE loss reach the lowest at about 60th epoch while the F1-bleu reach the best at about 14th epoch. Results are better when using the model saved at 14th epoch.

**Comment by guxd** [comment]
you can choose the 60th epoch in this case
